travis:
  secure:
    BINSTAR_TOKEN: VHCDH+O7ylSGpf8v8p+e9QBJOqqRFcOD6UZW/dbHhUqkMHZiJrlW5VJXu3Sn++op2wFIGIysnpac2nIqdE0UhXao3kfndOJsBX3dMX1kzK47jeKFP8mUz+t8YJ06YZghwRmQqfbB9yOZCvu8T+5dZlQ3BqLZwf7EF0uYEWNFVKTCkgWAmuJOXW1AgS9lGXCaQ+KCwOR6QLLQ4rnBX7Xh7BrI435tbrZmO2H4u5wZ1U4aHK/TVNwOmXba1veqrc5DUzLrHgfd5/2SPOd8S2HUR2XUlFsmmaIwa1K2ccR4pYD0Z+GHSz3cJkhWC/UfA0lF9PvYpJzF5MTKD3l/0Q3/qwJ/NiQHMLIlMGO799hk1J4L6ujiTYrk7lNwuF3OMfHUtDYvRUM3Nl42jDSHoLQoEJZ960jb1zQBLWx3LlBErkcPnNPYd+UHZJb4wa0CDOvlC8AxlMAdROpVKVThTMDhfODdMFRqVtYCfn7ftgPhpySeqzlwSZbhn6S9nBOrd6+c/aHsKzOA0zfNCOr8yc2XbIFT/NkNtkRns5Gc2GGU6CLZzTZL7DVY8A1tuiPOAUTjYN+Sj3gv1RciJNzgwEWCCq9BgYqLliBwy6BycwAd5i/xRg1z6s+mAeHzQzE9AMGIw/n6Xd5E2uyLdUOi7zG7MU8pOy1KL/vLuYLWAmLzFx0=
appveyor:
  secure:
    BINSTAR_TOKEN: MP4hZYylDyUWEsrt3u3cod2sbFeRwUziH02mvQOdbjsTO/l1yIxDkP/76rSIjcGC
