travis:
  secure:
    BINSTAR_TOKEN: PbpULDWzbrx4+OZJ94H8a6yMlKVprj2qh4evg+7XzAYDexay80fAPJ1NxA9dKrkczZS/yP9azsI+Z7k7ogQ5ToDLZB3Rd6QB2DtkgV7vRom3hYSETGABEIAfAbbdIJjocNfKvSXOxphsIptQtnnchm8SJrFYKGNf2QTS8BQeEc7Bog8y9bMEKWlkFvAdg7yZAw0EfrIllVJzgkQ2Laq82qjp8puQgGNoCv/nTw7axwq0NDkTMvjTfr9aWbGJ6t+OpbG5BvXn7gX/Eyk+CCXjFXFWmJfOh+sH9QVEQub2oZqTs/P+DWlJIbyvVUtRnr6e875m10nQ+a7DurTA3LmcES+Pau1gaepOVhINyBRk9nmAhEJCmDLybmEWXiXBYlsgeapNQsdKymWpeBM01wdLcP3n4nWl3W7cLQ/E4aDdQTSoHzS7Z6mCRqjPO3d8xuqgnX94ydKrF4D4C9BxLLaogRUfNLow/gikzmb4HzIqkuIWmllhfjM9zRqsAOHd+EwWJygO5ud+kqQPKfEZ8qIgPnDaRe0ht+orQ0fDANE2dsHoVm2RWwwPtmOrwTUdayqCHnp7fpuL2OcPmu1LTjBCTgxH9X3d9Qa6U5I7j/80ME5jfMKKP19FBbMRrzvXjD1NFMMdWkwv2PSeFsDZVwqPInXNif5kprEaWl2mFhA2R6U=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
