travis:
  secure:
    BINSTAR_TOKEN: KIkyLXUV2J6n0jInFh4TN6fBQrVvS82aeUafXPGYDa6wl9fwKyeuM5asa7/f+aPii0fhavBMsGhLS50lXETuyXWQ2VKIBsV3c7t+nPj1vepOrNh4UgOunolCrnYK+hvRFheB+0hI7HHLV1+83Ku4VO+d23jcVdyhK08h6hsglRm1sEo0b0THohrmRkv2/w9Mf3MZLMDJMfdbdNAvNUqO4S1ZwM8xJj6OFYaft1ieljSP8I5hb2XMbBHF2JKaqcjIVMOyGHEB74aEGa+Dpl+U1tOgojBw0Q7H7y0dU5jfxhtkFR4GaWzGXqkrU3M/zBMjLFa8aeLx/emKHpz75FNUBOfrZ5L4DxTA06d9jkUUG5J/CNVafCxYguFre4VseUGei6jNLg1Vh3uV0pf+LMo+kRwgSp/ei7PX4068cN4tf7pCYMj+9KU+XW7FhXoZ4tLTaHhXX6UgbM6tQOmJo47P8cAWx8LGkbBKoFL7GsWTFmSz3mnawdGSd6tVtXe3itqtxbSIYOq4DkUeobJgm+zwKlh3uJCrzTS13h92OOFsweytYRc5/u4z3XkcadXZ2aFMeyf3LYVR3u5KRsLKZtu9lX9jerrioL78dQTvb780MzjeLR7cPgE4t3NNee7CsXQ7S5U4UYRa5N3ku9fhbVZfRTrTGNcWZ7Vg4xp9Ppwjeas=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
